REACTIVITY_SERIES_ELEMENTS = {
    'Potassium': 24,
    'Sodium': 23,
    'Lithium': 22,
    'Barium': 21,
    'Strontium': 20,
    'Calcium': 19,
    'Magnesium': 18,
    'Aluminium': 17,
    'Manganese': 16,
    'Zinc': 15,
    'Chromium': 14,
    'Iron': 13,
    'Cadmium': 12,
    'Cobalt': 11,
    'Nickel': 10,
    'Tin': 9,
    'Lead': 8,
    'Hydrogen': 7,
    'Antimony': 6,
    'Bismuth': 5,
    'Copper': 4,
    'Mercury': 3,
    'Silver': 2,
    'Gold': 1,
    'Platinum': 0,
}

REACTIVITY_SERIES_SYMBOLS = {
    'K': 'Potassium',
    'Na': 'Sodium',
    'Li': 'Lithium',
    'Ba': 'Barium',
    'Sr': 'Strontium',
    'Ca': 'Calcium',
    'Mg': 'Magnesium',
    'Al': 'Aluminium',
    'Mn': 'Manganese',
    'Zn': 'Zinc',
    'Cr': 'Chromium',
    'Fe': 'Iron',
    'Cd': 'Cadmium',
    'Co': 'Cobalt',
    'Ni': 'Nickel',
    'Sn': 'Tin',
    'Pb': 'Lead',
    'H': 'Hydrogen',
    'Sb': 'Antimony',
    'Bi': 'Bismuth',
    'Cu': 'Copper',
    'Hg': 'Mercury',
    'Ag': 'Silver',
    'Au': 'Gold',
    'Pt': 'Platinum'
}

HALOGENS = [
    'Fluorine',
    'Chlorine',
    'Bromine',
    'Iodine',
    'Astatine'
]